// Barrel re-export — semua import lama dari '@/lib/api' tetap bekerja
export { default } from './api/client';
export * from './api/products';
export * from './api/production-categories';
export * from './api/transactions';
export * from './api/customers';
export * from './api/cashflow';
export * from './api/reports';
export * from './api/finance-analytics';
export * from './api/settings';
export * from './api/hpp';
export * from './api/invoices';
export * from './api/whatsapp';
export * from './api/opname';
export * from './api/production';
export * from './api/suppliers';
export * from './api/backup';
export * from './api/click-counting';
export * from './api/designers';
export * from './api/branch-inbox';
export * from './api/crm';
export * from './api/work-orders';
export * from './api/discord';
export * from './api/landing';
export * from './api/articles';
